services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: pdf-rag-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${DB_NAME:-pdf_rag_db}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - pdf-rag-network

  # ChromaDB Service
  chromadb:
    image: chromadb/chroma:latest
    container_name: pdf-rag-chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=${CHROMA_ANONYMIZED_TELEMETRY:-TRUE}
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma_db
    volumes:
      - chromadb_data:/chroma/chroma_db
    networks:
      - pdf-rag-network

  # Ollama Service
  ollama:
    image: ollama/ollama:latest
    container_name: pdf-rag-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - pdf-rag-network

volumes:
  mongodb_data:
    driver: local
  chromadb_data:
    driver: local
  ollama_data:
    driver: local

networks:
  pdf-rag-network:
    driver: bridge